/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActivityCategory } from './activityCategory';
import { FilterField } from './filterField';
import { User } from './user';

/**
* Represents a change in an issue or in its related entities. In the UI, you see these changes as the Activity stream. It shows a feed of all updates of the issue: issue history, comments, attachments, VCS changes, work items, and so on.
*/
export class ActivityItem {
    'author'?: User;
    'timestamp'?: number;
    'removed'?: object;
    'added'?: object;
    'target'?: object;
    'targetMember'?: string;
    'field'?: FilterField;
    'category'?: ActivityCategory;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "author",
            "baseName": "author",
            "type": "User"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "number"
        },
        {
            "name": "removed",
            "baseName": "removed",
            "type": "object"
        },
        {
            "name": "added",
            "baseName": "added",
            "type": "object"
        },
        {
            "name": "target",
            "baseName": "target",
            "type": "object"
        },
        {
            "name": "targetMember",
            "baseName": "targetMember",
            "type": "string"
        },
        {
            "name": "field",
            "baseName": "field",
            "type": "FilterField"
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "ActivityCategory"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ActivityItem.attributeTypeMap;
    }
}

