/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AgileColumnFieldValue } from './agileColumnFieldValue';
import { ColumnSettings } from './columnSettings';
import { WIPLimit } from './wIPLimit';

/**
* Represents settings for a single board column
*/
export class AgileColumn {
    'presentation'?: string;
    'isResolved'?: boolean;
    'ordinal'?: number;
    'parent'?: ColumnSettings;
    'wipLimit'?: WIPLimit;
    'fieldValues'?: Array<AgileColumnFieldValue>;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "presentation",
            "baseName": "presentation",
            "type": "string"
        },
        {
            "name": "isResolved",
            "baseName": "isResolved",
            "type": "boolean"
        },
        {
            "name": "ordinal",
            "baseName": "ordinal",
            "type": "number"
        },
        {
            "name": "parent",
            "baseName": "parent",
            "type": "ColumnSettings"
        },
        {
            "name": "wipLimit",
            "baseName": "wipLimit",
            "type": "WIPLimit"
        },
        {
            "name": "fieldValues",
            "baseName": "fieldValues",
            "type": "Array<AgileColumnFieldValue>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AgileColumn.attributeTypeMap;
    }
}

