/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AgileStatus } from './agileStatus';
import { ColorCoding } from './colorCoding';
import { ColumnSettings } from './columnSettings';
import { CustomField } from './customField';
import { Project } from './project';
import { Sprint } from './sprint';
import { SprintsSettings } from './sprintsSettings';
import { SwimlaneSettings } from './swimlaneSettings';
import { User } from './user';
import { UserGroup } from './userGroup';

/**
* Represents an agile board configuration.
*/
export class Agile {
    'name'?: string;
    'owner'?: User;
    'visibleFor'?: UserGroup;
    'visibleForProjectBased'?: boolean;
    'updateableBy'?: UserGroup;
    'updateableByProjectBased'?: boolean;
    'orphansAtTheTop'?: boolean;
    'hideOrphansSwimlane'?: boolean;
    'estimationField'?: CustomField;
    'originalEstimationField'?: CustomField;
    'projects'?: Array<Project>;
    'sprints'?: Array<Sprint>;
    'currentSprint'?: Sprint;
    'columnSettings'?: ColumnSettings;
    'swimlaneSettings'?: SwimlaneSettings;
    'sprintsSettings'?: SprintsSettings;
    'colorCoding'?: ColorCoding;
    'status'?: AgileStatus;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "User"
        },
        {
            "name": "visibleFor",
            "baseName": "visibleFor",
            "type": "UserGroup"
        },
        {
            "name": "visibleForProjectBased",
            "baseName": "visibleForProjectBased",
            "type": "boolean"
        },
        {
            "name": "updateableBy",
            "baseName": "updateableBy",
            "type": "UserGroup"
        },
        {
            "name": "updateableByProjectBased",
            "baseName": "updateableByProjectBased",
            "type": "boolean"
        },
        {
            "name": "orphansAtTheTop",
            "baseName": "orphansAtTheTop",
            "type": "boolean"
        },
        {
            "name": "hideOrphansSwimlane",
            "baseName": "hideOrphansSwimlane",
            "type": "boolean"
        },
        {
            "name": "estimationField",
            "baseName": "estimationField",
            "type": "CustomField"
        },
        {
            "name": "originalEstimationField",
            "baseName": "originalEstimationField",
            "type": "CustomField"
        },
        {
            "name": "projects",
            "baseName": "projects",
            "type": "Array<Project>"
        },
        {
            "name": "sprints",
            "baseName": "sprints",
            "type": "Array<Sprint>"
        },
        {
            "name": "currentSprint",
            "baseName": "currentSprint",
            "type": "Sprint"
        },
        {
            "name": "columnSettings",
            "baseName": "columnSettings",
            "type": "ColumnSettings"
        },
        {
            "name": "swimlaneSettings",
            "baseName": "swimlaneSettings",
            "type": "SwimlaneSettings"
        },
        {
            "name": "sprintsSettings",
            "baseName": "sprintsSettings",
            "type": "SprintsSettings"
        },
        {
            "name": "colorCoding",
            "baseName": "colorCoding",
            "type": "ColorCoding"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "AgileStatus"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Agile.attributeTypeMap;
    }
}

