/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DateFormatDescriptor } from './dateFormatDescriptor';
import { Logo } from './logo';
import { TimeZoneDescriptor } from './timeZoneDescriptor';

/**
* Represents the Visual settings of the YouTrack service.
*/
export class AppearanceSettings {
    'timeZone'?: TimeZoneDescriptor;
    'dateFieldFormat'?: DateFormatDescriptor;
    'logo'?: Logo;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "timeZone",
            "baseName": "timeZone",
            "type": "TimeZoneDescriptor"
        },
        {
            "name": "dateFieldFormat",
            "baseName": "dateFieldFormat",
            "type": "DateFormatDescriptor"
        },
        {
            "name": "logo",
            "baseName": "logo",
            "type": "Logo"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AppearanceSettings.attributeTypeMap;
    }
}

