/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Article } from './article';
import { ArticleAttachment } from './articleAttachment';
import { User } from './user';
import { Visibility } from './visibility';

/**
* Represents a comment to an article.
*/
export class ArticleComment {
    'text'?: string;
    'created'?: number;
    'updated'?: number;
    'author'?: User;
    'article'?: Article;
    'attachments'?: Array<ArticleAttachment>;
    'visibility'?: Visibility;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "number"
        },
        {
            "name": "author",
            "baseName": "author",
            "type": "User"
        },
        {
            "name": "article",
            "baseName": "article",
            "type": "Article"
        },
        {
            "name": "attachments",
            "baseName": "attachments",
            "type": "Array<ArticleAttachment>"
        },
        {
            "name": "visibility",
            "baseName": "visibility",
            "type": "Visibility"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ArticleComment.attributeTypeMap;
    }
}

