/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FilterField } from './filterField';
import { SwimlaneEntityAttributeValue } from './swimlaneEntityAttributeValue';

export class AttributeBasedSwimlaneSettingsAllOf {
    'field'?: FilterField;
    'values'?: Array<SwimlaneEntityAttributeValue>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "FilterField"
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<SwimlaneEntityAttributeValue>"
        }    ];

    static getAttributeTypeMap() {
        return AttributeBasedSwimlaneSettingsAllOf.attributeTypeMap;
    }
}

