/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BuildBundleElementAllOf } from './buildBundleElementAllOf';
import { Bundle } from './bundle';
import { BundleElement } from './bundleElement';
import { FieldStyle } from './fieldStyle';

/**
* Represents a build - a single element of a builds bundle.
*/
export class BuildBundleElement extends BundleElement {
    'assembleDate'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "assembleDate",
            "baseName": "assembleDate",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(BuildBundleElement.attributeTypeMap);
    }
}

