/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BuildBundleElement } from './buildBundleElement';

export class BuildBundleAllOf {
    'values'?: Array<BuildBundleElement>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<BuildBundleElement>"
        }    ];

    static getAttributeTypeMap() {
        return BuildBundleAllOf.attributeTypeMap;
    }
}

