/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BaseBundle } from './baseBundle';
import { BuildBundleAllOf } from './buildBundleAllOf';
import { BuildBundleElement } from './buildBundleElement';

/**
* Represents a set of builds in YouTrack.
*/
export class BuildBundle extends BaseBundle {
    'values'?: Array<BuildBundleElement>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<BuildBundleElement>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(BuildBundle.attributeTypeMap);
    }
}

