/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AgileColumn } from './agileColumn';
import { CustomField } from './customField';

/**
* Agile board columns settings.
*/
export class ColumnSettings {
    'field'?: CustomField;
    'columns'?: Array<AgileColumn>;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "CustomField"
        },
        {
            "name": "columns",
            "baseName": "columns",
            "type": "Array<AgileColumn>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ColumnSettings.attributeTypeMap;
    }
}

