/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CommandVisibility } from './commandVisibility';
import { Issue } from './issue';
import { ParsedCommand } from './parsedCommand';
import { Suggestion } from './suggestion';

/**
* Represents list of command and related comment in YouTrack. Can be used to either apply a command or get command suggestions.
*/
export class CommandList {
    'comment'?: string;
    'visibility'?: CommandVisibility;
    'query'?: string;
    'caret'?: number;
    'silent'?: boolean;
    'usesMarkdown'?: boolean;
    'runAs'?: string;
    'commands'?: Array<ParsedCommand>;
    'issues'?: Array<Issue>;
    'suggestions'?: Array<Suggestion>;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string"
        },
        {
            "name": "visibility",
            "baseName": "visibility",
            "type": "CommandVisibility"
        },
        {
            "name": "query",
            "baseName": "query",
            "type": "string"
        },
        {
            "name": "caret",
            "baseName": "caret",
            "type": "number"
        },
        {
            "name": "silent",
            "baseName": "silent",
            "type": "boolean"
        },
        {
            "name": "usesMarkdown",
            "baseName": "usesMarkdown",
            "type": "boolean"
        },
        {
            "name": "runAs",
            "baseName": "runAs",
            "type": "string"
        },
        {
            "name": "commands",
            "baseName": "commands",
            "type": "Array<ParsedCommand>"
        },
        {
            "name": "issues",
            "baseName": "issues",
            "type": "Array<Issue>"
        },
        {
            "name": "suggestions",
            "baseName": "suggestions",
            "type": "Array<Suggestion>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CommandList.attributeTypeMap;
    }
}

