/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IssueAttachment } from './issueAttachment';
import { IssueComment } from './issueComment';

export class CommentAttachmentsActivityItemAllOf {
    'target'?: IssueComment;
    'removed'?: Array<IssueAttachment>;
    'added'?: Array<IssueAttachment>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "target",
            "baseName": "target",
            "type": "IssueComment"
        },
        {
            "name": "removed",
            "baseName": "removed",
            "type": "Array<IssueAttachment>"
        },
        {
            "name": "added",
            "baseName": "added",
            "type": "Array<IssueAttachment>"
        }    ];

    static getAttributeTypeMap() {
        return CommentAttachmentsActivityItemAllOf.attributeTypeMap;
    }
}

