/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActivityCategory } from './activityCategory';
import { ActivityItem } from './activityItem';
import { FilterField } from './filterField';
import { User } from './user';

/**
* Represents an action when an entity is created or deleted in an issue. For example, a new comment is created in the issue.
*/
export class CreatedDeletedActivityItem extends ActivityItem {

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(CreatedDeletedActivityItem.attributeTypeMap);
    }
}

