/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CustomFieldDefaults } from './customFieldDefaults';
import { FieldType } from './fieldType';
import { ProjectCustomField } from './projectCustomField';

/**
* Represents a custom field in YouTrack.
*/
export class CustomField {
    'name'?: string;
    'localizedName'?: string;
    'fieldType'?: FieldType;
    'isAutoAttached'?: boolean;
    'isDisplayedInIssueList'?: boolean;
    'ordinal'?: number;
    'aliases'?: string;
    'fieldDefaults'?: CustomFieldDefaults;
    'hasRunningJob'?: boolean;
    'isUpdateable'?: boolean;
    'instances'?: Array<ProjectCustomField>;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "localizedName",
            "baseName": "localizedName",
            "type": "string"
        },
        {
            "name": "fieldType",
            "baseName": "fieldType",
            "type": "FieldType"
        },
        {
            "name": "isAutoAttached",
            "baseName": "isAutoAttached",
            "type": "boolean"
        },
        {
            "name": "isDisplayedInIssueList",
            "baseName": "isDisplayedInIssueList",
            "type": "boolean"
        },
        {
            "name": "ordinal",
            "baseName": "ordinal",
            "type": "number"
        },
        {
            "name": "aliases",
            "baseName": "aliases",
            "type": "string"
        },
        {
            "name": "fieldDefaults",
            "baseName": "fieldDefaults",
            "type": "CustomFieldDefaults"
        },
        {
            "name": "hasRunningJob",
            "baseName": "hasRunningJob",
            "type": "boolean"
        },
        {
            "name": "isUpdateable",
            "baseName": "isUpdateable",
            "type": "boolean"
        },
        {
            "name": "instances",
            "baseName": "instances",
            "type": "Array<ProjectCustomField>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomField.attributeTypeMap;
    }
}

