/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CustomField } from './customField';

/**
* Represents default project-related settings of the custom field. These settings are applied at the moment when the custom field is attached to a project. After that, any changes in default settings do not affect the field settings for this project.
*/
export class CustomFieldDefaults {
    'canBeEmpty'?: boolean;
    'emptyFieldText'?: string;
    'isPublic'?: boolean;
    'parent'?: CustomField;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "canBeEmpty",
            "baseName": "canBeEmpty",
            "type": "boolean"
        },
        {
            "name": "emptyFieldText",
            "baseName": "emptyFieldText",
            "type": "string"
        },
        {
            "name": "isPublic",
            "baseName": "isPublic",
            "type": "boolean"
        },
        {
            "name": "parent",
            "baseName": "parent",
            "type": "CustomField"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomFieldDefaults.attributeTypeMap;
    }
}

