/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StorageEntry } from './storageEntry';

/**
* Represents email settings for this YouTrack installation.
*/
export class EmailSettings {
    'isEnabled'?: boolean;
    'host'?: string;
    'port'?: number;
    'mailProtocol'?: EmailSettings.MailProtocolEnum;
    'anonymous'?: boolean;
    'login'?: string;
    'sslKey'?: StorageEntry;
    'from'?: string;
    'replyTo'?: string;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "isEnabled",
            "baseName": "isEnabled",
            "type": "boolean"
        },
        {
            "name": "host",
            "baseName": "host",
            "type": "string"
        },
        {
            "name": "port",
            "baseName": "port",
            "type": "number"
        },
        {
            "name": "mailProtocol",
            "baseName": "mailProtocol",
            "type": "EmailSettings.MailProtocolEnum"
        },
        {
            "name": "anonymous",
            "baseName": "anonymous",
            "type": "boolean"
        },
        {
            "name": "login",
            "baseName": "login",
            "type": "string"
        },
        {
            "name": "sslKey",
            "baseName": "sslKey",
            "type": "StorageEntry"
        },
        {
            "name": "from",
            "baseName": "from",
            "type": "string"
        },
        {
            "name": "replyTo",
            "baseName": "replyTo",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EmailSettings.attributeTypeMap;
    }
}

export namespace EmailSettings {
    export enum MailProtocolEnum {
        Smtp = <any> 'SMTP',
        Smtps = <any> 'SMTPS',
        SmtpTls = <any> 'SMTP_TLS'
    }
}
