/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BaseBundle } from './baseBundle';
import { EnumBundleAllOf } from './enumBundleAllOf';
import { EnumBundleElement } from './enumBundleElement';

/**
* Represents an enumerated set of values in YouTrack.
*/
export class EnumBundle extends BaseBundle {
    'values'?: Array<EnumBundleElement>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<EnumBundleElement>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(EnumBundle.attributeTypeMap);
    }
}

