/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DateFormatDescriptor } from './dateFormatDescriptor';
import { LocaleDescriptor } from './localeDescriptor';
import { TimeZoneDescriptor } from './timeZoneDescriptor';

/**
* Represents the user profile in YouTrack.
*/
export class GeneralUserProfile {
    'dateFieldFormat'?: DateFormatDescriptor;
    'timezone'?: TimeZoneDescriptor;
    'locale'?: LocaleDescriptor;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dateFieldFormat",
            "baseName": "dateFieldFormat",
            "type": "DateFormatDescriptor"
        },
        {
            "name": "timezone",
            "baseName": "timezone",
            "type": "TimeZoneDescriptor"
        },
        {
            "name": "locale",
            "baseName": "locale",
            "type": "LocaleDescriptor"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GeneralUserProfile.attributeTypeMap;
    }
}

