/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WorkItemType } from './workItemType';
import { WorkTimeSettings } from './workTimeSettings';

/**
* Represents time tracking settings of your server.
*/
export class GlobalTimeTrackingSettings {
    'workItemTypes'?: Array<WorkItemType>;
    'workTimeSettings'?: WorkTimeSettings;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "workItemTypes",
            "baseName": "workItemTypes",
            "type": "Array<WorkItemType>"
        },
        {
            "name": "workTimeSettings",
            "baseName": "workTimeSettings",
            "type": "WorkTimeSettings"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GlobalTimeTrackingSettings.attributeTypeMap;
    }
}

