/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AppearanceSettings } from './appearanceSettings';
import { License } from './license';
import { LocaleSettings } from './localeSettings';
import { NotificationSettings } from './notificationSettings';
import { RestCorsSettings } from './restCorsSettings';
import { SystemSettings } from './systemSettings';

/**
* Represents application-wide settings.
*/
export class GlobalSettings {
    'systemSettings'?: SystemSettings;
    'notificationSettings'?: NotificationSettings;
    'restSettings'?: RestCorsSettings;
    'appearanceSettings'?: AppearanceSettings;
    'localeSettings'?: LocaleSettings;
    'license'?: License;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "systemSettings",
            "baseName": "systemSettings",
            "type": "SystemSettings"
        },
        {
            "name": "notificationSettings",
            "baseName": "notificationSettings",
            "type": "NotificationSettings"
        },
        {
            "name": "restSettings",
            "baseName": "restSettings",
            "type": "RestCorsSettings"
        },
        {
            "name": "appearanceSettings",
            "baseName": "appearanceSettings",
            "type": "AppearanceSettings"
        },
        {
            "name": "localeSettings",
            "baseName": "localeSettings",
            "type": "LocaleSettings"
        },
        {
            "name": "license",
            "baseName": "license",
            "type": "License"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GlobalSettings.attributeTypeMap;
    }
}

