/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CustomField } from './customField';
import { GroupProjectCustomFieldAllOf } from './groupProjectCustomFieldAllOf';
import { Project } from './project';
import { ProjectCustomField } from './projectCustomField';
import { UserGroup } from './userGroup';

/**
* Represents project settings for group custom field.
*/
export class GroupProjectCustomField extends ProjectCustomField {
    'defaultValues'?: Array<UserGroup>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "defaultValues",
            "baseName": "defaultValues",
            "type": "Array<UserGroup>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(GroupProjectCustomField.attributeTypeMap);
    }
}

