/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FilterField } from './filterField';
import { IssueBasedSwimlaneSettingsAllOf } from './issueBasedSwimlaneSettingsAllOf';
import { SwimlaneSettings } from './swimlaneSettings';
import { SwimlaneValue } from './swimlaneValue';

/**
* Swimlane settings for the case, when each swimlane is represented by an issue and contains this issue\'s subtasks.
*/
export class IssueBasedSwimlaneSettings extends SwimlaneSettings {
    'field'?: FilterField;
    'defaultCardType'?: SwimlaneValue;
    'values'?: Array<SwimlaneValue>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "FilterField"
        },
        {
            "name": "defaultCardType",
            "baseName": "defaultCardType",
            "type": "SwimlaneValue"
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<SwimlaneValue>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(IssueBasedSwimlaneSettings.attributeTypeMap);
    }
}

