/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IssueFolder } from './issueFolder';

/**
* Represents the number of issues in a search result.
*/
export class IssueCountResponse {
    'count'?: number;
    'unresolvedOnly'?: boolean;
    'query'?: string;
    'folder'?: IssueFolder;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "count",
            "baseName": "count",
            "type": "number"
        },
        {
            "name": "unresolvedOnly",
            "baseName": "unresolvedOnly",
            "type": "boolean"
        },
        {
            "name": "query",
            "baseName": "query",
            "type": "string"
        },
        {
            "name": "folder",
            "baseName": "folder",
            "type": "IssueFolder"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return IssueCountResponse.attributeTypeMap;
    }
}

