/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Represents the settings of a link type in YouTrack.
*/
export class IssueLinkType {
    'name'?: string;
    'localizedName'?: string;
    'sourceToTarget'?: string;
    'localizedSourceToTarget'?: string;
    'targetToSource'?: string;
    'localizedTargetToSource'?: string;
    'directed'?: boolean;
    'aggregation'?: boolean;
    'readOnly'?: boolean;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "localizedName",
            "baseName": "localizedName",
            "type": "string"
        },
        {
            "name": "sourceToTarget",
            "baseName": "sourceToTarget",
            "type": "string"
        },
        {
            "name": "localizedSourceToTarget",
            "baseName": "localizedSourceToTarget",
            "type": "string"
        },
        {
            "name": "targetToSource",
            "baseName": "targetToSource",
            "type": "string"
        },
        {
            "name": "localizedTargetToSource",
            "baseName": "localizedTargetToSource",
            "type": "string"
        },
        {
            "name": "directed",
            "baseName": "directed",
            "type": "boolean"
        },
        {
            "name": "aggregation",
            "baseName": "aggregation",
            "type": "boolean"
        },
        {
            "name": "readOnly",
            "baseName": "readOnly",
            "type": "boolean"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return IssueLinkType.attributeTypeMap;
    }
}

