/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FieldStyle } from './fieldStyle';
import { Issue } from './issue';
import { IssueTagAllOf } from './issueTagAllOf';
import { User } from './user';
import { UserGroup } from './userGroup';
import { WatchFolder } from './watchFolder';

/**
* Represents an issue tag.
*/
export class IssueTag extends WatchFolder {
    'issues'?: Array<Issue>;
    'color'?: FieldStyle;
    'untagOnResolve'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "issues",
            "baseName": "issues",
            "type": "Array<Issue>"
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "FieldStyle"
        },
        {
            "name": "untagOnResolve",
            "baseName": "untagOnResolve",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(IssueTag.attributeTypeMap);
    }
}

