/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DuplicateVote } from './duplicateVote';
import { User } from './user';

/**
* Represents users that have voted for the issue or its duplicates.
*/
export class IssueVoters {
    'hasVote'?: boolean;
    'original'?: Array<User>;
    'duplicate'?: Array<DuplicateVote>;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "hasVote",
            "baseName": "hasVote",
            "type": "boolean"
        },
        {
            "name": "original",
            "baseName": "original",
            "type": "Array<User>"
        },
        {
            "name": "duplicate",
            "baseName": "duplicate",
            "type": "Array<DuplicateVote>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return IssueVoters.attributeTypeMap;
    }
}

