/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DurationValue } from './durationValue';
import { Issue } from './issue';
import { User } from './user';
import { WorkItemType } from './workItemType';

/**
* Represents a work item in an issue.
*/
export class IssueWorkItem {
    'author'?: User;
    'creator'?: User;
    'text'?: string;
    'textPreview'?: string;
    'type'?: WorkItemType;
    'created'?: number;
    'updated'?: number;
    'duration'?: DurationValue;
    'date'?: number;
    'issue'?: Issue;
    'usesMarkdown'?: boolean;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "author",
            "baseName": "author",
            "type": "User"
        },
        {
            "name": "creator",
            "baseName": "creator",
            "type": "User"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        },
        {
            "name": "textPreview",
            "baseName": "textPreview",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "WorkItemType"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "number"
        },
        {
            "name": "duration",
            "baseName": "duration",
            "type": "DurationValue"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "number"
        },
        {
            "name": "issue",
            "baseName": "issue",
            "type": "Issue"
        },
        {
            "name": "usesMarkdown",
            "baseName": "usesMarkdown",
            "type": "boolean"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return IssueWorkItem.attributeTypeMap;
    }
}

