/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IssueWatcher } from './issueWatcher';

/**
* Represents users that are subscribed to notifications about the issue.
*/
export class IssueWatchers {
    'hasStar'?: boolean;
    'issueWatchers'?: Array<IssueWatcher>;
    'duplicateWatchers'?: Array<IssueWatcher>;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "hasStar",
            "baseName": "hasStar",
            "type": "boolean"
        },
        {
            "name": "issueWatchers",
            "baseName": "issueWatchers",
            "type": "Array<IssueWatcher>"
        },
        {
            "name": "duplicateWatchers",
            "baseName": "duplicateWatchers",
            "type": "Array<IssueWatcher>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return IssueWatchers.attributeTypeMap;
    }
}

