/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActivityCategory } from './activityCategory';
import { FilterField } from './filterField';
import { IssueResolvedActivityItemAllOf } from './issueResolvedActivityItemAllOf';
import { SimpleValueActivityItem } from './simpleValueActivityItem';
import { User } from './user';

/**
* Represents an event when a user resolves an issue.
*/
export class IssueResolvedActivityItem extends SimpleValueActivityItem {
    // @ts-ignore
    'removed'?: number;
    // @ts-ignore
    'added'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "removed",
            "baseName": "removed",
            "type": "number"
        },
        {
            "name": "added",
            "baseName": "added",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(IssueResolvedActivityItem.attributeTypeMap);
    }
}

