/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class IssueResolvedActivityItemAllOf {
    'removed'?: number;
    'added'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "removed",
            "baseName": "removed",
            "type": "number"
        },
        {
            "name": "added",
            "baseName": "added",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return IssueResolvedActivityItemAllOf.attributeTypeMap;
    }
}

