/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Issue } from './issue';
import { IssueAttachment } from './issueAttachment';
import { User } from './user';
import { Visibility } from './visibility';

/**
* Represents an existing issue comment.
*/
export class IssueComment {
    'text'?: string;
    'usesMarkdown'?: boolean;
    'textPreview'?: string;
    'created'?: number;
    'updated'?: number;
    'author'?: User;
    'issue'?: Issue;
    'attachments'?: Array<IssueAttachment>;
    'visibility'?: Visibility;
    'deleted'?: boolean;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        },
        {
            "name": "usesMarkdown",
            "baseName": "usesMarkdown",
            "type": "boolean"
        },
        {
            "name": "textPreview",
            "baseName": "textPreview",
            "type": "string"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "number"
        },
        {
            "name": "author",
            "baseName": "author",
            "type": "User"
        },
        {
            "name": "issue",
            "baseName": "issue",
            "type": "Issue"
        },
        {
            "name": "attachments",
            "baseName": "attachments",
            "type": "Array<IssueAttachment>"
        },
        {
            "name": "visibility",
            "baseName": "visibility",
            "type": "Visibility"
        },
        {
            "name": "deleted",
            "baseName": "deleted",
            "type": "boolean"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return IssueComment.attributeTypeMap;
    }
}

