/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { LimitedVisibilityAllOf } from './limitedVisibilityAllOf';
import { User } from './user';
import { UserGroup } from './userGroup';
import { Visibility } from './visibility';

/**
* Represents visibility limited to several users and/or groups.
*/
export class LimitedVisibility extends Visibility {
    'permittedGroups'?: Array<UserGroup>;
    'permittedUsers'?: Array<User>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "permittedGroups",
            "baseName": "permittedGroups",
            "type": "Array<UserGroup>"
        },
        {
            "name": "permittedUsers",
            "baseName": "permittedUsers",
            "type": "Array<User>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(LimitedVisibility.attributeTypeMap);
    }
}

