/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActivityCategory } from './activityCategory';
import { FilterField } from './filterField';
import { Issue } from './issue';
import { IssueCreatedActivityItemAllOf } from './issueCreatedActivityItemAllOf';
import { MultiValueActivityItem } from './multiValueActivityItem';
import { User } from './user';

/**
* Represents a change in the `issues` attribute of an IssueLink entity. That is, each issue has the `links` attribute that contains an array of IssueLink entities. Each of them represents a link between the target issue and a collection of issues. For example, a set of issues to which the target one is linked as \"Duplicated by\". The change in the list of these issues is represented by `LinksActivityItem` entity.
*/
export class LinksActivityItem extends MultiValueActivityItem {
    'target'?: Issue;
    'removed'?: Array<Issue>;
    'added'?: Array<Issue>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "target",
            "baseName": "target",
            "type": "Issue"
        },
        {
            "name": "removed",
            "baseName": "removed",
            "type": "Array<Issue>"
        },
        {
            "name": "added",
            "baseName": "added",
            "type": "Array<Issue>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(LinksActivityItem.attributeTypeMap);
    }
}

