/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IssueTag } from './issueTag';
import { SavedQuery } from './savedQuery';
import { User } from './user';
import { UserProfiles } from './userProfiles';

/**
* Represents the currently logged in user in YouTrack.
*/
export class Me extends User {

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(Me.attributeTypeMap);
    }
}

