/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DatabaseMultiValueIssueCustomField } from './databaseMultiValueIssueCustomField';
import { MultiUserIssueCustomFieldAllOf } from './multiUserIssueCustomFieldAllOf';
import { ProjectCustomField } from './projectCustomField';
import { User } from './user';

/**
* Represents the issue custom field of the `user` type that can have multiple values.
*/
export class MultiUserIssueCustomField extends DatabaseMultiValueIssueCustomField {
    'value'?: Array<User>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "Array<User>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(MultiUserIssueCustomField.attributeTypeMap);
    }
}

