/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DatabaseMultiValueIssueCustomField } from './databaseMultiValueIssueCustomField';
import { EnumBundleElement } from './enumBundleElement';
import { MultiEnumIssueCustomFieldAllOf } from './multiEnumIssueCustomFieldAllOf';
import { ProjectCustomField } from './projectCustomField';

/**
* Represents the issue custom field of the `enum` type that can have multiple values.
*/
export class MultiEnumIssueCustomField extends DatabaseMultiValueIssueCustomField {
    'value'?: Array<EnumBundleElement>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "Array<EnumBundleElement>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(MultiEnumIssueCustomField.attributeTypeMap);
    }
}

