/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DatabaseMultiValueIssueCustomField } from './databaseMultiValueIssueCustomField';
import { MultiOwnedIssueCustomFieldAllOf } from './multiOwnedIssueCustomFieldAllOf';
import { OwnedBundleElement } from './ownedBundleElement';
import { ProjectCustomField } from './projectCustomField';

/**
* Represents the issue custom field of the `ownedField` type that can have multiple values. The predefined Subsystem field is the example of the owned fields.
*/
export class MultiOwnedIssueCustomField extends DatabaseMultiValueIssueCustomField {
    'value'?: Array<OwnedBundleElement>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "Array<OwnedBundleElement>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(MultiOwnedIssueCustomField.attributeTypeMap);
    }
}

