/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EmailSettings } from './emailSettings';
import { JabberSettings } from './jabberSettings';

/**
* Represents the Notifications settings of the YouTrack service.
*/
export class NotificationSettings {
    'emailSettings'?: EmailSettings;
    'jabberSettings'?: JabberSettings;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "emailSettings",
            "baseName": "emailSettings",
            "type": "EmailSettings"
        },
        {
            "name": "jabberSettings",
            "baseName": "jabberSettings",
            "type": "JabberSettings"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return NotificationSettings.attributeTypeMap;
    }
}

