/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Represents the notification settings in the profile of the specific user.
*/
export class NotificationsUserProfile {
    'notifyOnOwnChanges'?: boolean;
    'jabberNotificationsEnabled'?: boolean;
    'emailNotificationsEnabled'?: boolean;
    'mentionNotificationsEnabled'?: boolean;
    'duplicateClusterNotificationsEnabled'?: boolean;
    'mailboxIntegrationNotificationsEnabled'?: boolean;
    'usePlainTextEmails'?: boolean;
    'autoWatchOnComment'?: boolean;
    'autoWatchOnCreate'?: boolean;
    'autoWatchOnVote'?: boolean;
    'autoWatchOnUpdate'?: boolean;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "notifyOnOwnChanges",
            "baseName": "notifyOnOwnChanges",
            "type": "boolean"
        },
        {
            "name": "jabberNotificationsEnabled",
            "baseName": "jabberNotificationsEnabled",
            "type": "boolean"
        },
        {
            "name": "emailNotificationsEnabled",
            "baseName": "emailNotificationsEnabled",
            "type": "boolean"
        },
        {
            "name": "mentionNotificationsEnabled",
            "baseName": "mentionNotificationsEnabled",
            "type": "boolean"
        },
        {
            "name": "duplicateClusterNotificationsEnabled",
            "baseName": "duplicateClusterNotificationsEnabled",
            "type": "boolean"
        },
        {
            "name": "mailboxIntegrationNotificationsEnabled",
            "baseName": "mailboxIntegrationNotificationsEnabled",
            "type": "boolean"
        },
        {
            "name": "usePlainTextEmails",
            "baseName": "usePlainTextEmails",
            "type": "boolean"
        },
        {
            "name": "autoWatchOnComment",
            "baseName": "autoWatchOnComment",
            "type": "boolean"
        },
        {
            "name": "autoWatchOnCreate",
            "baseName": "autoWatchOnCreate",
            "type": "boolean"
        },
        {
            "name": "autoWatchOnVote",
            "baseName": "autoWatchOnVote",
            "type": "boolean"
        },
        {
            "name": "autoWatchOnUpdate",
            "baseName": "autoWatchOnUpdate",
            "type": "boolean"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return NotificationsUserProfile.attributeTypeMap;
    }
}

