/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BundleCustomFieldDefaults } from './bundleCustomFieldDefaults';
import { CustomField } from './customField';
import { OwnedBundle } from './ownedBundle';
import { OwnedBundleCustomFieldDefaultsAllOf } from './ownedBundleCustomFieldDefaultsAllOf';
import { OwnedBundleElement } from './ownedBundleElement';

/**
* Default settings for the owned-type field.
*/
export class OwnedBundleCustomFieldDefaults extends BundleCustomFieldDefaults {
    'bundle'?: OwnedBundle;
    'defaultValues'?: Array<OwnedBundleElement>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "bundle",
            "baseName": "bundle",
            "type": "OwnedBundle"
        },
        {
            "name": "defaultValues",
            "baseName": "defaultValues",
            "type": "Array<OwnedBundleElement>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(OwnedBundleCustomFieldDefaults.attributeTypeMap);
    }
}

