/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Bundle } from './bundle';
import { BundleElement } from './bundleElement';
import { FieldStyle } from './fieldStyle';
import { OwnedBundleElementAllOf } from './ownedBundleElementAllOf';
import { User } from './user';

/**
* Represents a single owned value of a set. For example, a subsystem.
*/
export class OwnedBundleElement extends BundleElement {
    'owner'?: User;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "owner",
            "baseName": "owner",
            "type": "User"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(OwnedBundleElement.attributeTypeMap);
    }
}

