/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OwnedBundle } from './ownedBundle';
import { OwnedBundleElement } from './ownedBundleElement';

export class OwnedBundleCustomFieldDefaultsAllOf {
    'bundle'?: OwnedBundle;
    'defaultValues'?: Array<OwnedBundleElement>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "bundle",
            "baseName": "bundle",
            "type": "OwnedBundle"
        },
        {
            "name": "defaultValues",
            "baseName": "defaultValues",
            "type": "Array<OwnedBundleElement>"
        }    ];

    static getAttributeTypeMap() {
        return OwnedBundleCustomFieldDefaultsAllOf.attributeTypeMap;
    }
}

