/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FilterField } from './filterField';

/**
* Represents a predefined field of the issue. Predefined fields are always present in an issue and             |cannot be customized in a project. For example, `project`, `created`,             |`updated`, `tags`, and so on.
*/
export class PredefinedFilterField extends FilterField {

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(PredefinedFilterField.attributeTypeMap);
    }
}

