/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Issue } from './issue';
import { User } from './user';
import { UserGroup } from './userGroup';

export class ProjectAllOf {
    'startingNumber'?: number;
    'shortName'?: string;
    'description'?: string;
    'leader'?: User;
    'createdBy'?: User;
    'issues'?: Array<Issue>;
    'customFields'?: object;
    'archived'?: boolean;
    'fromEmail'?: string;
    'replyToEmail'?: string;
    'template'?: boolean;
    'iconUrl'?: string;
    'team'?: UserGroup;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "startingNumber",
            "baseName": "startingNumber",
            "type": "number"
        },
        {
            "name": "shortName",
            "baseName": "shortName",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "leader",
            "baseName": "leader",
            "type": "User"
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "User"
        },
        {
            "name": "issues",
            "baseName": "issues",
            "type": "Array<Issue>"
        },
        {
            "name": "customFields",
            "baseName": "customFields",
            "type": "object"
        },
        {
            "name": "archived",
            "baseName": "archived",
            "type": "boolean"
        },
        {
            "name": "fromEmail",
            "baseName": "fromEmail",
            "type": "string"
        },
        {
            "name": "replyToEmail",
            "baseName": "replyToEmail",
            "type": "string"
        },
        {
            "name": "template",
            "baseName": "template",
            "type": "boolean"
        },
        {
            "name": "iconUrl",
            "baseName": "iconUrl",
            "type": "string"
        },
        {
            "name": "team",
            "baseName": "team",
            "type": "UserGroup"
        }    ];

    static getAttributeTypeMap() {
        return ProjectAllOf.attributeTypeMap;
    }
}

