/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Project } from './project';
import { ProjectCustomField } from './projectCustomField';
import { WorkItemType } from './workItemType';

/**
* Represents time tracking settings of the project.
*/
export class ProjectTimeTrackingSettings {
    'enabled'?: boolean;
    'estimate'?: ProjectCustomField;
    'timeSpent'?: ProjectCustomField;
    'workItemTypes'?: Array<WorkItemType>;
    'project'?: Project;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean"
        },
        {
            "name": "estimate",
            "baseName": "estimate",
            "type": "ProjectCustomField"
        },
        {
            "name": "timeSpent",
            "baseName": "timeSpent",
            "type": "ProjectCustomField"
        },
        {
            "name": "workItemTypes",
            "baseName": "workItemTypes",
            "type": "Array<WorkItemType>"
        },
        {
            "name": "project",
            "baseName": "project",
            "type": "Project"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ProjectTimeTrackingSettings.attributeTypeMap;
    }
}

