/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ColorCoding } from './colorCoding';
import { ProjectBasedColorCodingAllOf } from './projectBasedColorCodingAllOf';
import { ProjectColor } from './projectColor';

/**
* Lets you set a color for a card based on its project.
*/
export class ProjectBasedColorCoding extends ColorCoding {
    'projectColors'?: Array<ProjectColor>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "projectColors",
            "baseName": "projectColors",
            "type": "Array<ProjectColor>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(ProjectBasedColorCoding.attributeTypeMap);
    }
}

