/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Represents the Resource Sharing (CORS) configuration of the service.
*/
export class RestCorsSettings {
    'allowedOrigins'?: Array<string>;
    'allowAllOrigins'?: boolean;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "allowedOrigins",
            "baseName": "allowedOrigins",
            "type": "Array<string>"
        },
        {
            "name": "allowAllOrigins",
            "baseName": "allowAllOrigins",
            "type": "boolean"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RestCorsSettings.attributeTypeMap;
    }
}

