/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Issue } from './issue';
import { SavedQueryAllOf } from './savedQueryAllOf';
import { User } from './user';
import { UserGroup } from './userGroup';
import { WatchFolder } from './watchFolder';

/**
* Represents a saved search.
*/
export class SavedQuery extends WatchFolder {
    'query'?: string;
    'issues'?: Array<Issue>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "query",
            "baseName": "query",
            "type": "string"
        },
        {
            "name": "issues",
            "baseName": "issues",
            "type": "Array<Issue>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(SavedQuery.attributeTypeMap);
    }
}

