/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IssueFolder } from './issueFolder';
import { Suggestion } from './suggestion';

/**
* Represents the list of search suggestions for the currently entered search query.
*/
export class SearchSuggestions {
    'caret'?: number;
    'ignoreUnresolvedSetting'?: boolean;
    'query'?: string;
    'suggestions'?: Array<Suggestion>;
    'folders'?: Array<IssueFolder>;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "caret",
            "baseName": "caret",
            "type": "number"
        },
        {
            "name": "ignoreUnresolvedSetting",
            "baseName": "ignoreUnresolvedSetting",
            "type": "boolean"
        },
        {
            "name": "query",
            "baseName": "query",
            "type": "string"
        },
        {
            "name": "suggestions",
            "baseName": "suggestions",
            "type": "Array<Suggestion>"
        },
        {
            "name": "folders",
            "baseName": "folders",
            "type": "Array<IssueFolder>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SearchSuggestions.attributeTypeMap;
    }
}

