/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DatabaseSingleValueIssueCustomField } from './databaseSingleValueIssueCustomField';
import { ProjectCustomField } from './projectCustomField';
import { SingleGroupIssueCustomFieldAllOf } from './singleGroupIssueCustomFieldAllOf';
import { UserGroup } from './userGroup';

/**
* Represents the issue custom field of the `group` type that can only have a single value.
*/
export class SingleGroupIssueCustomField extends DatabaseSingleValueIssueCustomField {
    'value'?: UserGroup;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "UserGroup"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(SingleGroupIssueCustomField.attributeTypeMap);
    }
}

