/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CustomField } from './customField';
import { Sprint } from './sprint';

/**
* Describes sprints configuration.
*/
export class SprintsSettings {
    'isExplicit'?: boolean;
    'cardOnSeveralSprints'?: boolean;
    'defaultSprint'?: Sprint;
    'disableSprints'?: boolean;
    'explicitQuery'?: string;
    'sprintSyncField'?: CustomField;
    'hideSubtasksOfCards'?: boolean;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "isExplicit",
            "baseName": "isExplicit",
            "type": "boolean"
        },
        {
            "name": "cardOnSeveralSprints",
            "baseName": "cardOnSeveralSprints",
            "type": "boolean"
        },
        {
            "name": "defaultSprint",
            "baseName": "defaultSprint",
            "type": "Sprint"
        },
        {
            "name": "disableSprints",
            "baseName": "disableSprints",
            "type": "boolean"
        },
        {
            "name": "explicitQuery",
            "baseName": "explicitQuery",
            "type": "string"
        },
        {
            "name": "sprintSyncField",
            "baseName": "sprintSyncField",
            "type": "CustomField"
        },
        {
            "name": "hideSubtasksOfCards",
            "baseName": "hideSubtasksOfCards",
            "type": "boolean"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SprintsSettings.attributeTypeMap;
    }
}

