/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Agile } from './agile';
import { Issue } from './issue';

/**
* Represents a sprint that is associated with an agile board. Each sprint can include issues from one or more projects.
*/
export class Sprint {
    'agile'?: Agile;
    'name'?: string;
    'goal'?: string;
    'start'?: number;
    'finish'?: number;
    'archived'?: boolean;
    'isDefault'?: boolean;
    'issues'?: Array<Issue>;
    'unresolvedIssuesCount'?: number;
    'previousSprint'?: Sprint;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "agile",
            "baseName": "agile",
            "type": "Agile"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "goal",
            "baseName": "goal",
            "type": "string"
        },
        {
            "name": "start",
            "baseName": "start",
            "type": "number"
        },
        {
            "name": "finish",
            "baseName": "finish",
            "type": "number"
        },
        {
            "name": "archived",
            "baseName": "archived",
            "type": "boolean"
        },
        {
            "name": "isDefault",
            "baseName": "isDefault",
            "type": "boolean"
        },
        {
            "name": "issues",
            "baseName": "issues",
            "type": "Array<Issue>"
        },
        {
            "name": "unresolvedIssuesCount",
            "baseName": "unresolvedIssuesCount",
            "type": "number"
        },
        {
            "name": "previousSprint",
            "baseName": "previousSprint",
            "type": "Sprint"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Sprint.attributeTypeMap;
    }
}

