/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Bundle } from './bundle';
import { FieldStyle } from './fieldStyle';
import { LocalizableBundleElement } from './localizableBundleElement';
import { StateBundleElementAllOf } from './stateBundleElementAllOf';

/**
* Represents the state of an issue in YouTrack.
*/
export class StateBundleElement extends LocalizableBundleElement {
    'isResolved'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "isResolved",
            "baseName": "isResolved",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(StateBundleElement.attributeTypeMap);
    }
}

