/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Represents query suggestion.
*/
export class Suggestion {
    'completionStart'?: number;
    'completionEnd'?: number;
    'matchingStart'?: number;
    'matchingEnd'?: number;
    'caret'?: number;
    'description'?: string;
    'option'?: string;
    'prefix'?: string;
    'suffix'?: string;
    'group'?: string;
    'icon'?: string;
    'auxiliaryIcon'?: string;
    'className'?: string;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "completionStart",
            "baseName": "completionStart",
            "type": "number"
        },
        {
            "name": "completionEnd",
            "baseName": "completionEnd",
            "type": "number"
        },
        {
            "name": "matchingStart",
            "baseName": "matchingStart",
            "type": "number"
        },
        {
            "name": "matchingEnd",
            "baseName": "matchingEnd",
            "type": "number"
        },
        {
            "name": "caret",
            "baseName": "caret",
            "type": "number"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "option",
            "baseName": "option",
            "type": "string"
        },
        {
            "name": "prefix",
            "baseName": "prefix",
            "type": "string"
        },
        {
            "name": "suffix",
            "baseName": "suffix",
            "type": "string"
        },
        {
            "name": "group",
            "baseName": "group",
            "type": "string"
        },
        {
            "name": "icon",
            "baseName": "icon",
            "type": "string"
        },
        {
            "name": "auxiliaryIcon",
            "baseName": "auxiliaryIcon",
            "type": "string"
        },
        {
            "name": "className",
            "baseName": "className",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Suggestion.attributeTypeMap;
    }
}

