/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Represents the System settings that affect core functionality of YouTrack.
*/
export class SystemSettings {
    'baseUrl'?: string;
    'maxUploadFileSize'?: number;
    'maxExportItems'?: number;
    'administratorEmail'?: string;
    'allowStatisticsCollection'?: boolean;
    'isApplicationReadOnly'?: boolean;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "baseUrl",
            "baseName": "baseUrl",
            "type": "string"
        },
        {
            "name": "maxUploadFileSize",
            "baseName": "maxUploadFileSize",
            "type": "number"
        },
        {
            "name": "maxExportItems",
            "baseName": "maxExportItems",
            "type": "number"
        },
        {
            "name": "administratorEmail",
            "baseName": "administratorEmail",
            "type": "string"
        },
        {
            "name": "allowStatisticsCollection",
            "baseName": "allowStatisticsCollection",
            "type": "boolean"
        },
        {
            "name": "isApplicationReadOnly",
            "baseName": "isApplicationReadOnly",
            "type": "boolean"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SystemSettings.attributeTypeMap;
    }
}

