/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActivityCategory } from './activityCategory';
import { FilterField } from './filterField';
import { Issue } from './issue';
import { IssueTag } from './issueTag';
import { MultiValueActivityItem } from './multiValueActivityItem';
import { TagsActivityItemAllOf } from './tagsActivityItemAllOf';
import { User } from './user';

/**
* Represents a change in the list of tags of an issue.
*/
export class TagsActivityItem extends MultiValueActivityItem {
    'target'?: Issue;
    'removed'?: Array<IssueTag>;
    'added'?: Array<IssueTag>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "target",
            "baseName": "target",
            "type": "Issue"
        },
        {
            "name": "removed",
            "baseName": "removed",
            "type": "Array<IssueTag>"
        },
        {
            "name": "added",
            "baseName": "added",
            "type": "Array<IssueTag>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(TagsActivityItem.attributeTypeMap);
    }
}

