/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OnlineUsers } from './onlineUsers';

/**
* Telemetry data of the YouTrack installation.
*/
export class Telemetry {
    'installationFolder'?: string;
    'databaseLocation'?: string;
    'logsLocation'?: string;
    'availableProcessors'?: number;
    'availableMemory'?: string;
    'allocatedMemory'?: string;
    'usedMemory'?: string;
    'uptime'?: string;
    'startedTime'?: number;
    'databaseBackgroundThreads'?: number;
    'pendingAsyncJobs'?: number;
    'cachedResultsCountInDBQueriesCache'?: number;
    'databaseQueriesCacheHitRate'?: string;
    'blobStringsCacheHitRate'?: string;
    'totalTransactions'?: number;
    'transactionsPerSecond'?: string;
    'requestsPerSecond'?: string;
    'databaseSize'?: string;
    'fullDatabaseSize'?: string;
    'textIndexSize'?: string;
    'onlineUsers'?: OnlineUsers;
    'reportCalculatorThreads'?: number;
    'notificationAnalyzerThreads'?: number;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "installationFolder",
            "baseName": "installationFolder",
            "type": "string"
        },
        {
            "name": "databaseLocation",
            "baseName": "databaseLocation",
            "type": "string"
        },
        {
            "name": "logsLocation",
            "baseName": "logsLocation",
            "type": "string"
        },
        {
            "name": "availableProcessors",
            "baseName": "availableProcessors",
            "type": "number"
        },
        {
            "name": "availableMemory",
            "baseName": "availableMemory",
            "type": "string"
        },
        {
            "name": "allocatedMemory",
            "baseName": "allocatedMemory",
            "type": "string"
        },
        {
            "name": "usedMemory",
            "baseName": "usedMemory",
            "type": "string"
        },
        {
            "name": "uptime",
            "baseName": "uptime",
            "type": "string"
        },
        {
            "name": "startedTime",
            "baseName": "startedTime",
            "type": "number"
        },
        {
            "name": "databaseBackgroundThreads",
            "baseName": "databaseBackgroundThreads",
            "type": "number"
        },
        {
            "name": "pendingAsyncJobs",
            "baseName": "pendingAsyncJobs",
            "type": "number"
        },
        {
            "name": "cachedResultsCountInDBQueriesCache",
            "baseName": "cachedResultsCountInDBQueriesCache",
            "type": "number"
        },
        {
            "name": "databaseQueriesCacheHitRate",
            "baseName": "databaseQueriesCacheHitRate",
            "type": "string"
        },
        {
            "name": "blobStringsCacheHitRate",
            "baseName": "blobStringsCacheHitRate",
            "type": "string"
        },
        {
            "name": "totalTransactions",
            "baseName": "totalTransactions",
            "type": "number"
        },
        {
            "name": "transactionsPerSecond",
            "baseName": "transactionsPerSecond",
            "type": "string"
        },
        {
            "name": "requestsPerSecond",
            "baseName": "requestsPerSecond",
            "type": "string"
        },
        {
            "name": "databaseSize",
            "baseName": "databaseSize",
            "type": "string"
        },
        {
            "name": "fullDatabaseSize",
            "baseName": "fullDatabaseSize",
            "type": "string"
        },
        {
            "name": "textIndexSize",
            "baseName": "textIndexSize",
            "type": "string"
        },
        {
            "name": "onlineUsers",
            "baseName": "onlineUsers",
            "type": "OnlineUsers"
        },
        {
            "name": "reportCalculatorThreads",
            "baseName": "reportCalculatorThreads",
            "type": "number"
        },
        {
            "name": "notificationAnalyzerThreads",
            "baseName": "notificationAnalyzerThreads",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Telemetry.attributeTypeMap;
    }
}

