/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActivityCategory } from './activityCategory';
import { CustomFieldActivityItem } from './customFieldActivityItem';
import { FilterField } from './filterField';
import { Issue } from './issue';
import { TextCustomFieldActivityItemAllOf } from './textCustomFieldActivityItemAllOf';
import { User } from './user';

/**
* Represents an activity that affects a custom field of the `text` type of an issue.
*/
export class TextCustomFieldActivityItem extends CustomFieldActivityItem {
    'target'?: Issue;
    // @ts-ignore
    'removed'?: string;
    // @ts-ignore
    'added'?: string;
    'markup'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "target",
            "baseName": "target",
            "type": "Issue"
        },
        {
            "name": "removed",
            "baseName": "removed",
            "type": "string"
        },
        {
            "name": "added",
            "baseName": "added",
            "type": "string"
        },
        {
            "name": "markup",
            "baseName": "markup",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(TextCustomFieldActivityItem.attributeTypeMap);
    }
}

