/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActivityCategory } from './activityCategory';
import { FilterField } from './filterField';
import { SimpleValueActivityItem } from './simpleValueActivityItem';
import { TextMarkupActivityItemAllOf } from './textMarkupActivityItemAllOf';
import { User } from './user';

/**
* Represents a change in a `String`-type attribute with the support of markup: `description` in an Issue or IssueWorkItem, and the `text` of the IssueComment. This entity lets you get the rendered text after the change.
*/
export class TextMarkupActivityItem extends SimpleValueActivityItem {
    // @ts-ignore
    'removed'?: string;
    // @ts-ignore
    'added'?: string;
    'markup'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "removed",
            "baseName": "removed",
            "type": "string"
        },
        {
            "name": "added",
            "baseName": "added",
            "type": "string"
        },
        {
            "name": "markup",
            "baseName": "markup",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(TextMarkupActivityItem.attributeTypeMap);
    }
}

