/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Project } from './project';

/**
* Represents a group of users.
*/
export class UserGroup {
    'name'?: string;
    'ringId'?: string;
    'usersCount'?: number;
    'icon'?: string;
    'allUsersGroup'?: boolean;
    'teamForProject'?: Project;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "ringId",
            "baseName": "ringId",
            "type": "string"
        },
        {
            "name": "usersCount",
            "baseName": "usersCount",
            "type": "number"
        },
        {
            "name": "icon",
            "baseName": "icon",
            "type": "string"
        },
        {
            "name": "allUsersGroup",
            "baseName": "allUsersGroup",
            "type": "boolean"
        },
        {
            "name": "teamForProject",
            "baseName": "teamForProject",
            "type": "Project"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UserGroup.attributeTypeMap;
    }
}

