/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GeneralUserProfile } from './generalUserProfile';
import { NotificationsUserProfile } from './notificationsUserProfile';
import { TimeTrackingUserProfile } from './timeTrackingUserProfile';

export class UserProfiles {
    'general'?: GeneralUserProfile;
    'notifications'?: NotificationsUserProfile;
    'timetracking'?: TimeTrackingUserProfile;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "general",
            "baseName": "general",
            "type": "GeneralUserProfile"
        },
        {
            "name": "notifications",
            "baseName": "notifications",
            "type": "NotificationsUserProfile"
        },
        {
            "name": "timetracking",
            "baseName": "timetracking",
            "type": "TimeTrackingUserProfile"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UserProfiles.attributeTypeMap;
    }
}

