/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CustomField } from './customField';
import { CustomFieldDefaults } from './customFieldDefaults';
import { User } from './user';
import { UserBundle } from './userBundle';
import { UserCustomFieldDefaultsAllOf } from './userCustomFieldDefaultsAllOf';

/**
* Represents default settings for the user-type field.
*/
export class UserCustomFieldDefaults extends CustomFieldDefaults {
    'bundle'?: UserBundle;
    'defaultValues'?: Array<User>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "bundle",
            "baseName": "bundle",
            "type": "UserBundle"
        },
        {
            "name": "defaultValues",
            "baseName": "defaultValues",
            "type": "Array<User>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(UserCustomFieldDefaults.attributeTypeMap);
    }
}

