/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActivityCategory } from './activityCategory';
import { CreatedDeletedActivityItem } from './createdDeletedActivityItem';
import { FilterField } from './filterField';
import { User } from './user';
import { VcsChangeActivityItemAllOf } from './vcsChangeActivityItemAllOf';

/**
* Represents an update in the list of VCSChanges of an issue.
*/
export class VcsChangeActivityItem extends CreatedDeletedActivityItem {
    'removed'?: object;
    'added'?: object;
    'author'?: User;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "removed",
            "baseName": "removed",
            "type": "object"
        },
        {
            "name": "added",
            "baseName": "added",
            "type": "object"
        },
        {
            "name": "author",
            "baseName": "author",
            "type": "User"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(VcsChangeActivityItem.attributeTypeMap);
    }
}

