/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IssueTag } from './issueTag';
import { SavedQuery } from './savedQuery';
import { User } from './user';
import { UserProfiles } from './userProfiles';
import { VcsUnresolvedUserAllOf } from './vcsUnresolvedUserAllOf';

/**
* Represents an author of a VCS change that could not be found in the list of YouTrack users.
*/
export class VcsUnresolvedUser extends User {
    'name'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(VcsUnresolvedUser.attributeTypeMap);
    }
}

