/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BaseBundle } from './baseBundle';
import { VersionBundleAllOf } from './versionBundleAllOf';
import { VersionBundleElement } from './versionBundleElement';

/**
* Represents a set of versions in YouTrack.
*/
export class VersionBundle extends BaseBundle {
    'values'?: Array<VersionBundleElement>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<VersionBundleElement>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(VersionBundle.attributeTypeMap);
    }
}

