/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UserGroup } from './userGroup';

export class VisibilityGroupActivityItemAllOf {
    'targetMember'?: string;
    'targetSubMember'?: string;
    'removed'?: Array<UserGroup>;
    'added'?: Array<UserGroup>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "targetMember",
            "baseName": "targetMember",
            "type": "string"
        },
        {
            "name": "targetSubMember",
            "baseName": "targetSubMember",
            "type": "string"
        },
        {
            "name": "removed",
            "baseName": "removed",
            "type": "Array<UserGroup>"
        },
        {
            "name": "added",
            "baseName": "added",
            "type": "Array<UserGroup>"
        }    ];

    static getAttributeTypeMap() {
        return VisibilityGroupActivityItemAllOf.attributeTypeMap;
    }
}

