/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActivityCategory } from './activityCategory';
import { FilterField } from './filterField';
import { MultiValueActivityItem } from './multiValueActivityItem';
import { User } from './user';
import { VisibilityActivityItemAllOf } from './visibilityActivityItemAllOf';

/**
* Represents the changes of properties responsible for visibility restriction. Can be <a href=\"api-entity-VisibilityGroupActivityItem.xml\">VisibilityGroupActivityItem</a> or <a href=\"api-entity-VisibilityUserActivityItem.xml\">VisibilityUserActivityItem</a>
*/
export class VisibilityActivityItem extends MultiValueActivityItem {
    'targetMember'?: string;
    'targetSubMember'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "targetMember",
            "baseName": "targetMember",
            "type": "string"
        },
        {
            "name": "targetSubMember",
            "baseName": "targetSubMember",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(VisibilityActivityItem.attributeTypeMap);
    }
}

