/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActivityCategory } from './activityCategory';
import { FilterField } from './filterField';
import { User } from './user';
import { VisibilityActivityItem } from './visibilityActivityItem';
import { VisibilityUserActivityItemAllOf } from './visibilityUserActivityItemAllOf';

/**
* Represents the event when a user adds or removes a user to/from the Visibility settings of the target entity.
*/
export class VisibilityUserActivityItem extends VisibilityActivityItem {
    'targetMember'?: string;
    'targetSubMember'?: string;
    'removed'?: Array<User>;
    'added'?: Array<User>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "targetMember",
            "baseName": "targetMember",
            "type": "string"
        },
        {
            "name": "targetSubMember",
            "baseName": "targetSubMember",
            "type": "string"
        },
        {
            "name": "removed",
            "baseName": "removed",
            "type": "Array<User>"
        },
        {
            "name": "added",
            "baseName": "added",
            "type": "Array<User>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(VisibilityUserActivityItem.attributeTypeMap);
    }
}

