/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Issue } from './issue';
import { User } from './user';

export class VotersActivityItemAllOf {
    'target'?: Issue;
    'removed'?: Array<User>;
    'added'?: Array<User>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "target",
            "baseName": "target",
            "type": "Issue"
        },
        {
            "name": "removed",
            "baseName": "removed",
            "type": "Array<User>"
        },
        {
            "name": "added",
            "baseName": "added",
            "type": "Array<User>"
        }    ];

    static getAttributeTypeMap() {
        return VotersActivityItemAllOf.attributeTypeMap;
    }
}

