/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActivityCategory } from './activityCategory';
import { FilterField } from './filterField';
import { Issue } from './issue';
import { MultiValueActivityItem } from './multiValueActivityItem';
import { User } from './user';
import { VotersActivityItemAllOf } from './votersActivityItemAllOf';

/**
* Represents a change in the list of voters of an issue.
*/
export class VotersActivityItem extends MultiValueActivityItem {
    'target'?: Issue;
    'removed'?: Array<User>;
    'added'?: Array<User>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "target",
            "baseName": "target",
            "type": "Issue"
        },
        {
            "name": "removed",
            "baseName": "removed",
            "type": "Array<User>"
        },
        {
            "name": "added",
            "baseName": "added",
            "type": "Array<User>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(VotersActivityItem.attributeTypeMap);
    }
}

