/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IssueFolder } from './issueFolder';
import { User } from './user';
import { UserGroup } from './userGroup';
import { WatchFolderAllOf } from './watchFolderAllOf';

/**
* A `WatchFolder` is an `IssueFolder` that let you enable notifications for a set  of issues that it enfolds. It is a common abstract ancestor for saved searches and issue tags.
*/
export class WatchFolder extends IssueFolder {
    'owner'?: User;
    'visibleFor'?: UserGroup;
    'updateableBy'?: UserGroup;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "owner",
            "baseName": "owner",
            "type": "User"
        },
        {
            "name": "visibleFor",
            "baseName": "visibleFor",
            "type": "UserGroup"
        },
        {
            "name": "updateableBy",
            "baseName": "updateableBy",
            "type": "UserGroup"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WatchFolder.attributeTypeMap);
    }
}

