/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DurationValue } from './durationValue';
import { IssueWorkItem } from './issueWorkItem';

export class WorkItemDurationActivityItemAllOf {
    'target'?: IssueWorkItem;
    'removed'?: DurationValue;
    'added'?: DurationValue;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "target",
            "baseName": "target",
            "type": "IssueWorkItem"
        },
        {
            "name": "removed",
            "baseName": "removed",
            "type": "DurationValue"
        },
        {
            "name": "added",
            "baseName": "added",
            "type": "DurationValue"
        }    ];

    static getAttributeTypeMap() {
        return WorkItemDurationActivityItemAllOf.attributeTypeMap;
    }
}

