/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActivityCategory } from './activityCategory';
import { FilterField } from './filterField';
import { IssueWorkItem } from './issueWorkItem';
import { SingleValueActivityItem } from './singleValueActivityItem';
import { User } from './user';
import { WorkItemAuthorActivityItemAllOf } from './workItemAuthorActivityItemAllOf';

/**
* Represents a change in the `author` attribute of a work item.
*/
export class WorkItemAuthorActivityItem extends SingleValueActivityItem {
    'target'?: IssueWorkItem;
    'removed'?: User;
    'added'?: User;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "target",
            "baseName": "target",
            "type": "IssueWorkItem"
        },
        {
            "name": "removed",
            "baseName": "removed",
            "type": "User"
        },
        {
            "name": "added",
            "baseName": "added",
            "type": "User"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WorkItemAuthorActivityItem.attributeTypeMap);
    }
}

