/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IssueWorkItem } from './issueWorkItem';
import { User } from './user';

export class WorkItemAuthorActivityItemAllOf {
    'target'?: IssueWorkItem;
    'removed'?: User;
    'added'?: User;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "target",
            "baseName": "target",
            "type": "IssueWorkItem"
        },
        {
            "name": "removed",
            "baseName": "removed",
            "type": "User"
        },
        {
            "name": "added",
            "baseName": "added",
            "type": "User"
        }    ];

    static getAttributeTypeMap() {
        return WorkItemAuthorActivityItemAllOf.attributeTypeMap;
    }
}

