/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActivityCategory } from './activityCategory';
import { FilterField } from './filterField';
import { IssueWorkItem } from './issueWorkItem';
import { MultiValueActivityItem } from './multiValueActivityItem';
import { User } from './user';
import { WorkItemType } from './workItemType';
import { WorkItemTypeActivityItemAllOf } from './workItemTypeActivityItemAllOf';

/**
* Represents a change in the `type` attribute of the work item.
*/
export class WorkItemTypeActivityItem extends MultiValueActivityItem {
    'target'?: IssueWorkItem;
    'removed'?: Array<WorkItemType>;
    'added'?: Array<WorkItemType>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "target",
            "baseName": "target",
            "type": "IssueWorkItem"
        },
        {
            "name": "removed",
            "baseName": "removed",
            "type": "Array<WorkItemType>"
        },
        {
            "name": "added",
            "baseName": "added",
            "type": "Array<WorkItemType>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WorkItemTypeActivityItem.attributeTypeMap);
    }
}

