/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActivityCategory } from './activityCategory';
import { CreatedDeletedActivityItem } from './createdDeletedActivityItem';
import { FilterField } from './filterField';
import { IssueWorkItem } from './issueWorkItem';
import { User } from './user';
import { WorkItemActivityItemAllOf } from './workItemActivityItemAllOf';

/**
* Represents a change in a list of work items in an issue.
*/
export class WorkItemActivityItem extends CreatedDeletedActivityItem {
    'target'?: IssueWorkItem;
    'removed'?: Array<IssueWorkItem>;
    'added'?: Array<IssueWorkItem>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "target",
            "baseName": "target",
            "type": "IssueWorkItem"
        },
        {
            "name": "removed",
            "baseName": "removed",
            "type": "Array<IssueWorkItem>"
        },
        {
            "name": "added",
            "baseName": "added",
            "type": "Array<IssueWorkItem>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(WorkItemActivityItem.attributeTypeMap);
    }
}

