/**
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2021.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Work schedule settings.
*/
export class WorkTimeSettings {
    'minutesADay'?: number;
    'workDays'?: Array<number>;
    'firstDayOfWeek'?: number;
    'daysAWeek'?: number;
    'id'?: string;
    '$type'?: string;

    static discriminator: string | undefined = "$type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "minutesADay",
            "baseName": "minutesADay",
            "type": "number"
        },
        {
            "name": "workDays",
            "baseName": "workDays",
            "type": "Array<number>"
        },
        {
            "name": "firstDayOfWeek",
            "baseName": "firstDayOfWeek",
            "type": "number"
        },
        {
            "name": "daysAWeek",
            "baseName": "daysAWeek",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "$type",
            "baseName": "$type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return WorkTimeSettings.attributeTypeMap;
    }
}

